FROM golang:1.22 as build
WORKDIR /src
COPY go.mod ./
RUN go mod download
COPY . .
RUN --mount=type=cache,target=/root/.cache/go-build \
    CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /out/worker ./cmd/worker

FROM gcr.io/distroless/base-debian12
ENV PORT=50051
COPY --from=build /out/worker /worker
EXPOSE 50051
ENTRYPOINT ["/worker"]
