// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: worker.proto

package workerpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request from Load Generator
type WorkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DurationMs    int32                  `protobuf:"varint,1,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"` // CPU spin duration in milliseconds
	WorkMode      string                 `protobuf:"bytes,2,opt,name=work_mode,json=workMode,proto3" json:"work_mode,omitempty"`        // Work mode: "full" (default) or "echo"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkRequest) Reset() {
	*x = WorkRequest{}
	mi := &file_worker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkRequest) ProtoMessage() {}

func (x *WorkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkRequest.ProtoReflect.Descriptor instead.
func (*WorkRequest) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{0}
}

func (x *WorkRequest) GetDurationMs() int32 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *WorkRequest) GetWorkMode() string {
	if x != nil {
		return x.WorkMode
	}
	return ""
}

// Response from Worker
type WorkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	E2ELatencyMs  int64                  `protobuf:"varint,2,opt,name=e2e_latency_ms,json=e2eLatencyMs,proto3" json:"e2e_latency_ms,omitempty"`
	AvgCpuFreqKhz int64                  `protobuf:"varint,3,opt,name=avg_cpu_freq_khz,json=avgCpuFreqKhz,proto3" json:"avg_cpu_freq_khz,omitempty"` // Average CPU frequency (in kHz)
	Iterations    int64                  `protobuf:"varint,4,opt,name=iterations,proto3" json:"iterations,omitempty"`                                // number of busy-spin loops iterated
	// High-precision timestamps for data plane latency analysis
	ArrivalTimestampNs  int64 `protobuf:"varint,5,opt,name=arrival_timestamp_ns,json=arrivalTimestampNs,proto3" json:"arrival_timestamp_ns,omitempty"`      // Request arrival time (nanoseconds since epoch)
	PreBusyTimestampNs  int64 `protobuf:"varint,6,opt,name=pre_busy_timestamp_ns,json=preBusyTimestampNs,proto3" json:"pre_busy_timestamp_ns,omitempty"`    // Time before busy work starts
	PostBusyTimestampNs int64 `protobuf:"varint,7,opt,name=post_busy_timestamp_ns,json=postBusyTimestampNs,proto3" json:"post_busy_timestamp_ns,omitempty"` // Time after busy work completes
	ResponseTimestampNs int64 `protobuf:"varint,8,opt,name=response_timestamp_ns,json=responseTimestampNs,proto3" json:"response_timestamp_ns,omitempty"`   // Time when response is sent
	WorkerProcessingNs  int64 `protobuf:"varint,9,opt,name=worker_processing_ns,json=workerProcessingNs,proto3" json:"worker_processing_ns,omitempty"`      // Total worker processing time (post_busy - pre_busy)
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *WorkResponse) Reset() {
	*x = WorkResponse{}
	mi := &file_worker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkResponse) ProtoMessage() {}

func (x *WorkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkResponse.ProtoReflect.Descriptor instead.
func (*WorkResponse) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{1}
}

func (x *WorkResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *WorkResponse) GetE2ELatencyMs() int64 {
	if x != nil {
		return x.E2ELatencyMs
	}
	return 0
}

func (x *WorkResponse) GetAvgCpuFreqKhz() int64 {
	if x != nil {
		return x.AvgCpuFreqKhz
	}
	return 0
}

func (x *WorkResponse) GetIterations() int64 {
	if x != nil {
		return x.Iterations
	}
	return 0
}

func (x *WorkResponse) GetArrivalTimestampNs() int64 {
	if x != nil {
		return x.ArrivalTimestampNs
	}
	return 0
}

func (x *WorkResponse) GetPreBusyTimestampNs() int64 {
	if x != nil {
		return x.PreBusyTimestampNs
	}
	return 0
}

func (x *WorkResponse) GetPostBusyTimestampNs() int64 {
	if x != nil {
		return x.PostBusyTimestampNs
	}
	return 0
}

func (x *WorkResponse) GetResponseTimestampNs() int64 {
	if x != nil {
		return x.ResponseTimestampNs
	}
	return 0
}

func (x *WorkResponse) GetWorkerProcessingNs() int64 {
	if x != nil {
		return x.WorkerProcessingNs
	}
	return 0
}

var File_worker_proto protoreflect.FileDescriptor

const file_worker_proto_rawDesc = "" +
	"\n" +
	"\fworker.proto\x12\x06worker\"K\n" +
	"\vWorkRequest\x12\x1f\n" +
	"\vduration_ms\x18\x01 \x01(\x05R\n" +
	"durationMs\x12\x1b\n" +
	"\twork_mode\x18\x02 \x01(\tR\bworkMode\"\x95\x03\n" +
	"\fWorkResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12$\n" +
	"\x0ee2e_latency_ms\x18\x02 \x01(\x03R\fe2eLatencyMs\x12'\n" +
	"\x10avg_cpu_freq_khz\x18\x03 \x01(\x03R\ravgCpuFreqKhz\x12\x1e\n" +
	"\n" +
	"iterations\x18\x04 \x01(\x03R\n" +
	"iterations\x120\n" +
	"\x14arrival_timestamp_ns\x18\x05 \x01(\x03R\x12arrivalTimestampNs\x121\n" +
	"\x15pre_busy_timestamp_ns\x18\x06 \x01(\x03R\x12preBusyTimestampNs\x123\n" +
	"\x16post_busy_timestamp_ns\x18\a \x01(\x03R\x13postBusyTimestampNs\x122\n" +
	"\x15response_timestamp_ns\x18\b \x01(\x03R\x13responseTimestampNs\x120\n" +
	"\x14worker_processing_ns\x18\t \x01(\x03R\x12workerProcessingNs2D\n" +
	"\rWorkerService\x123\n" +
	"\x06DoWork\x12\x13.worker.WorkRequest\x1a\x14.worker.WorkResponseB\x15Z\x13./workerpb;workerpbb\x06proto3"

var (
	file_worker_proto_rawDescOnce sync.Once
	file_worker_proto_rawDescData []byte
)

func file_worker_proto_rawDescGZIP() []byte {
	file_worker_proto_rawDescOnce.Do(func() {
		file_worker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_worker_proto_rawDesc), len(file_worker_proto_rawDesc)))
	})
	return file_worker_proto_rawDescData
}

var file_worker_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_worker_proto_goTypes = []any{
	(*WorkRequest)(nil),  // 0: worker.WorkRequest
	(*WorkResponse)(nil), // 1: worker.WorkResponse
}
var file_worker_proto_depIdxs = []int32{
	0, // 0: worker.WorkerService.DoWork:input_type -> worker.WorkRequest
	1, // 1: worker.WorkerService.DoWork:output_type -> worker.WorkResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_worker_proto_init() }
func file_worker_proto_init() {
	if File_worker_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_worker_proto_rawDesc), len(file_worker_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_worker_proto_goTypes,
		DependencyIndexes: file_worker_proto_depIdxs,
		MessageInfos:      file_worker_proto_msgTypes,
	}.Build()
	File_worker_proto = out.File
	file_worker_proto_goTypes = nil
	file_worker_proto_depIdxs = nil
}
