apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: worker
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/maxScale: "2"
    spec:
      containerConcurrency: 1
      containers:
        - image: zj3214/worker:latest
          ports:
            - containerPort: 50051
              name: h2c
