apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: worker
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"   # Ensure at least 1 pod is always running
    spec:
      containerConcurrency: 1   # Only 1 request per pod at a time
      containers:
        - image: zj3214/worker:latest
          ports:
            - containerPort: 50051
              name: h2c
