apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: worker
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"   # at least 1 pod
    spec:
      containerConcurrency: 1                   # 1 request per pod
      containers:
      - image: zj3214/worker:latest
        ports:
          - containerPort: 50051
            name: h2c
          - containerPort: 9090
            name: metrics
        resources:
          requests:
            cpu: "1"
          limits:
            cpu: "1"
        # Optional probes
        readinessProbe:
          httpGet:
            path: /metrics
            port: 9090
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /metrics
            port: 9090
          initialDelaySeconds: 10
          periodSeconds: 20
